#define MOTOR_STEP_ANGLE 1.8
#define MOTOR_FULL_STEPS_REV 360 / MOTOR_STEP_ANGLE
#define MOTOR_STEPS_PER_90 (MOTOR_FULL_STEPS_REV / 4)
#define MOTOR_MICROSTEPPING 16
#define MOTOR_QUARTER_TURN (MOTOR_STEPS_PER_90 * MOTOR_MICROSTEPPING)
#define MOTOR_HALF_TURN (MOTOR_QUARTER_TURN * 2)

#define MOTOR_U_STEP 48
#define MOTOR_D_STEP 1
#define MOTOR_L_STEP 10
#define MOTOR_R_STEP 21
#define MOTOR_F_STEP 4
#define MOTOR_B_STEP 6

#define MOTOR_U_DIR 47
#define MOTOR_D_DIR 2
#define MOTOR_L_DIR 9
#define MOTOR_R_DIR 14
#define MOTOR_F_DIR 3
#define MOTOR_B_DIR 5

#define MOTOR_ENABLE 11

